-- Adicionar campos SEO ao modelo Project
ALTER TABLE "Project" 
ADD COLUMN IF NOT EXISTS "seoTitlePt" TEXT,
ADD COLUMN IF NOT EXISTS "seoTitleEn" TEXT,
ADD COLUMN IF NOT EXISTS "seoTitleEs" TEXT,
ADD COLUMN IF NOT EXISTS "seoTitleFr" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescPt" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescEn" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescEs" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescFr" TEXT,
ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[];
