/**
 * Script de Seed - Leads Kanban de Teste
 * Popula o banco com leads genéricos para testar o sistema Kanban
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const testLeads = [
  // 🎭 PERSONAS DIVERSAS - Simulando diferentes tipos de visitantes

  // 🆕 NOVOS LEADS (Status: NEW)
  {
    name: 'Maria Silva',
    email: 'maria.silva@mam.org.br',
    phone: '(21) 99999-1111',
    company: 'Museu de Arte Moderna - Rio',
    position: 'Curadora de Exposições',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Exposição Imersiva - História da Cidade',
    budget: 'R$ 150.000 - R$ 250.000',
    timeline: '6 meses',
    description: 'Interessados em criar uma exposição imersiva sobre a história do Rio de Janeiro. Queremos usar VR/AR e projeções mapeadas. Público alvo: estudantes e turistas.',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work/museus',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'museus-2026',
  },
  {
    name: 'João Santos',
    email: 'joao.santos@festivalcine.com',
    phone: '(11) 98888-2222',
    company: 'Festival Internacional de Cinema',
    position: 'Diretor de Programação',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação Interativa para Festival',
    budget: 'R$ 80.000 - R$ 120.000',
    timeline: '4 meses',
    description: 'Buscamos uma instalação interativa para o lobby do festival. Algo que envolva o público e crie experiência única. Referências: instalações do Sundance.',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work/festivais',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'festival-2026',
  },
  {
    name: 'Ana Costa',
    email: 'ana.costa@prefeitura.sp.gov.br',
    phone: '(11) 97777-3333',
    company: 'Prefeitura de São Paulo - Secretaria de Cultura',
    position: 'Coordenadora de Projetos Culturais',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Centro Cultural Digital',
    budget: 'R$ 500.000 - R$ 800.000',
    timeline: '12 meses',
    description: 'Projeto de centro cultural digital com múltiplas salas imersivas. Inclui VR, AR, projeções e interatividade. Público: comunidade local e escolas.',
    status: 'NEW',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'centro-cultural',
  },
  {
    name: 'Carlos Mendes',
    email: 'carlos.mendes@brandagency.com',
    phone: '(21) 96666-4444',
    company: 'Brand Agency',
    position: 'Diretor Criativo',
    leadType: 'CONTACT_FORM',
    projectType: 'Experiência de Marca - Lançamento',
    budget: 'R$ 200.000 - R$ 300.000',
    timeline: '3 meses',
    description: 'Cliente quer lançar novo produto com experiência imersiva em shopping. Precisa de algo impactante que gere buzz nas redes sociais.',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'brand-launch',
  },

  // 📞 CONTATO FEITO (Status: CONTACTED)
  {
    name: 'Patricia Lima',
    email: 'patricia.lima@museuhistoria.br',
    phone: '(11) 95555-5555',
    company: 'Museu de História Natural',
    position: 'Diretora de Educação',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Exposição Educacional Interativa',
    budget: 'R$ 100.000 - R$ 180.000',
    timeline: '5 meses',
    description: 'Exposição sobre evolução das espécies com elementos interativos. Foco em público escolar. Já tivemos call inicial, muito interessados.',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work/museus',
    utmSource: 'referral',
    utmMedium: 'word-of-mouth',
    utmCampaign: 'museu-historia',
    notes: 'Call realizada em 28/12. Cliente muito entusiasmado. Precisam de proposta até 15/01. Anick vai preparar moodboard.',
    lastContactAt: new Date('2025-12-28T14:30:00Z'),
  },
  {
    name: 'Roberto Alves',
    email: 'roberto.alves@institutoarte.org',
    phone: '(21) 94444-6666',
    company: 'Instituto de Arte Contemporânea',
    position: 'Curador',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação Artística - Bienal',
    budget: 'R$ 300.000 - R$ 500.000',
    timeline: '8 meses',
    description: 'Instalação para próxima Bienal de Arte. Conceito: realidade aumentada + esculturas físicas. Artista renomado envolvido.',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'bienal-2026',
    notes: 'Reunião presencial agendada para 10/01. Alberto vai participar. Projeto de grande visibilidade.',
    lastContactAt: new Date('2025-12-30T10:00:00Z'),
  },

  // 💼 PROPOSTA ENVIADA (Status: PROPOSAL_SENT)
  {
    name: 'Fernanda Rocha',
    email: 'fernanda.rocha@cidadecriativa.gov.br',
    phone: '(11) 93333-7777',
    company: 'Prefeitura - Cidade Criativa UNESCO',
    position: 'Secretária de Cultura',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Hub de Inovação Cultural',
    budget: 'R$ 1.000.000 - R$ 1.500.000',
    timeline: '18 meses',
    description: 'Projeto ambicioso: hub cultural com múltiplas salas, estúdio de produção, espaço de coworking. Fase 1: 3 salas imersivas.',
    status: 'PROPOSAL_SENT',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'cidade-criativa',
    notes: 'Proposta enviada em 20/12. Orçamento detalhado com 3 fases. Aguardando resposta do comitê de aprovação. Prazo: 20/01.',
    lastContactAt: new Date('2025-12-20T16:00:00Z'),
  },
  {
    name: 'Lucas Ferreira',
    email: 'lucas.ferreira@techstartup.com',
    phone: '(21) 92222-8888',
    company: 'Tech Startup - EdTech',
    position: 'CEO',
    leadType: 'CONTACT_FORM',
    projectType: 'Plataforma Educacional VR',
    budget: 'R$ 400.000 - R$ 600.000',
    timeline: '10 meses',
    description: 'Plataforma educacional com conteúdo VR para escolas. Parceria com secretarias de educação. Potencial de escala nacional.',
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'edtech-vr',
    notes: 'Proposta técnica enviada. Cliente revisando com investidores. Follow-up agendado para 12/01.',
    lastContactAt: new Date('2025-12-27T11:00:00Z'),
  },

  // 🤝 EM NEGOCIAÇÃO (Status: NEGOTIATION)
  {
    name: 'Juliana Martins',
    email: 'juliana.martins@museuarte.br',
    phone: '(11) 91111-9999',
    company: 'Museu de Arte de São Paulo',
    position: 'Diretora Executiva',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Exposição Permanente - Arte Digital',
    budget: 'R$ 250.000 - R$ 350.000',
    timeline: '6 meses',
    description: 'Exposição permanente sobre arte digital brasileira. Sala dedicada com instalações interativas e obras em VR/AR.',
    status: 'NEGOTIATION',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work/museus',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'masp-arte-digital',
    notes: 'Negociando escopo e timeline. Cliente quer reduzir orçamento em 20% mas manter escopo. Propondo fases. Reunião final: 08/01.',
    lastContactAt: new Date('2025-12-29T15:30:00Z'),
  },

  // ✅ GANHOS (Status: WON)
  {
    name: 'Ricardo Souza',
    email: 'ricardo.souza@festivalmusic.com',
    phone: '(21) 90000-0000',
    company: 'Festival de Música Eletrônica',
    position: 'Produtor Executivo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Instalação Visual - Palco Principal',
    budget: 'R$ 120.000 - R$ 180.000',
    timeline: '4 meses',
    description: 'Instalação visual para palco principal do festival. Mapping 3D, lasers, LED. Evento em março/2026.',
    status: 'WON',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work/festivais',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'festival-music',
    notes: '✅ PROJETO GANHO! Contrato assinado em 15/12. Início: 10/01. Equipe alocada: Anick (direção de arte), Alberto (produção).',
    lastContactAt: new Date('2025-12-15T17:00:00Z'),
  },
  {
    name: 'Sandra Oliveira',
    email: 'sandra.oliveira@marca.com.br',
    phone: '(11) 88888-1111',
    company: 'Marca de Luxo',
    position: 'Diretora de Marketing',
    leadType: 'CONTACT_FORM',
    projectType: 'Pop-up Experience - Shopping',
    budget: 'R$ 180.000 - R$ 250.000',
    timeline: '3 meses',
    description: 'Pop-up experience em shopping premium. Experiência imersiva de marca com elementos interativos e fotografia social.',
    status: 'WON',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'marca-luxo',
    notes: '✅ PROJETO GANHO! Contrato assinado. Evento em fevereiro. Cliente muito satisfeito com proposta.',
    lastContactAt: new Date('2025-12-22T14:00:00Z'),
  },

  // ❌ PERDIDOS (Status: LOST)
  {
    name: 'Marcos Silva',
    email: 'marcos.silva@empresa.com',
    phone: '(21) 87777-2222',
    company: 'Empresa de Eventos',
    position: 'Diretor',
    leadType: 'CONTACT_FORM',
    projectType: 'Evento Corporativo',
    budget: 'R$ 50.000 - R$ 80.000',
    timeline: '2 meses',
    description: 'Evento corporativo com elementos interativos. Orçamento muito apertado, não conseguimos atender.',
    status: 'LOST',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'evento-corporativo',
    notes: '❌ Perdido por orçamento. Cliente queria muito mais pelo valor oferecido. Não era fit para nosso perfil.',
    lastContactAt: new Date('2025-12-10T10:00:00Z'),
  },

  // 🎭 PERSONAS DIVERSAS - Simulando diferentes tipos de visitantes

  // 🧭 NAVEGADOR CURIOSO - Centro Cultural
  {
    name: 'Eduardo Mendes',
    email: 'eduardo.mendes@centrocultural.org.br',
    phone: '(11) 86666-3333',
    company: 'Centro Cultural Vila Madalena',
    position: 'Coordenador de Programação',
    leadType: 'CONTACT_FORM',
    projectType: 'Espaço Interativo Permanente',
    budget: 'R$ 120.000 - R$ 200.000',
    timeline: '8 meses',
    description: 'Estamos explorando possibilidades de criar um espaço interativo permanente no centro cultural. Visitamos vários sites de estúdios, mas o trabalho da Azimut chamou atenção. Queremos entender melhor o processo e ver exemplos similares.',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'organic',
    utmCampaign: 'exploracao',
    notes: 'Visitou: /work (múltiplas vezes), /solutions, /studio. Tempo no site: 15min. Muito curioso, explorando opções.',
  },

  // 🎨 INTERESSADO POÉTICO - Artista/Curator
  {
    name: 'Isabela Ferreira',
    email: 'isabela.ferreira@artecontemporanea.com',
    phone: '(21) 85555-4444',
    company: 'Galeria de Arte Contemporânea',
    position: 'Curadora Independente',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação Artística - Bienal',
    budget: 'R$ 180.000 - R$ 280.000',
    timeline: '10 meses',
    description: 'Busco criar uma experiência poética que funda tecnologia e arte. Não quero apenas algo técnico, mas algo que toque a alma. Vi o trabalho de vocês e senti uma conexão. Como podemos transformar conceitos abstratos em experiências imersivas?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'arte-poetica',
    notes: 'Linguagem muito poética e conceitual. Precisa de abordagem mais artística que comercial. Anick seria ideal para este lead.',
  },

  // 🏢 DIRETOR ALTO DESEMPENHO - Quer atividade para negócio
  {
    name: 'Roberto Almeida',
    email: 'roberto.almeida@corporacao.com.br',
    phone: '(11) 84444-5555',
    company: 'Corporação Multinacional - Divisão Inovação',
    position: 'Diretor de Inovação e Experiência',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Hub de Inovação - Experiências Imersivas',
    budget: 'R$ 800.000 - R$ 1.200.000',
    timeline: '12 meses',
    description: 'Precisamos de uma solução completa para nosso novo hub de inovação. Queremos múltiplas experiências imersivas que demonstrem nossas tecnologias. Orçamento não é problema, mas precisamos de resultados excepcionais. Vocês têm experiência com projetos corporativos de grande escala?',
    status: 'NEW',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'corporacao-inovacao',
    notes: 'Lead de alto valor. Diretor executivo, decisor. Orçamento grande. Precisamos resposta rápida e proposta impecável. Alberto deve liderar.',
  },

  // 🔧 FORNECEDOR - Quer parceria
  {
    name: 'Camila Rodrigues',
    email: 'camila.rodrigues@techsupplier.com',
    phone: '(21) 83333-6666',
    company: 'Tech Supplier - Equipamentos VR/AR',
    position: 'Gerente de Parcerias',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Estratégica',
    budget: 'Não se aplica',
    timeline: 'Contínuo',
    description: 'Somos fornecedores de equipamentos VR/AR de última geração. Gostaríamos de estabelecer uma parceria estratégica. Podemos fornecer equipamentos com desconto em troca de referências e cases. Vocês trabalham com quais marcas atualmente?',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/studio',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'fornecedor-parceria',
    notes: 'Fornecedor buscando parceria. Não é cliente direto, mas pode ser útil. Avaliar se faz sentido.',
  },

  // 🎓 INTERESSADO ACADÊMICO - Pesquisador
  {
    name: 'Dr. Paulo Henrique',
    email: 'paulo.henrique@universidade.edu.br',
    phone: '(11) 82222-7777',
    company: 'Universidade Federal - Laboratório de Mídias Digitais',
    position: 'Professor e Pesquisador',
    leadType: 'CONTACT_FORM',
    projectType: 'Projeto de Pesquisa - Aplicação de VR em Educação',
    budget: 'R$ 60.000 - R$ 100.000',
    timeline: '18 meses',
    description: 'Estamos desenvolvendo pesquisa sobre aplicação de VR em educação. Gostaríamos de contratar vocês para desenvolver protótipos que serão testados em escolas públicas. O projeto tem financiamento público (CNPq). Podemos discutir?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'academic',
    utmMedium: 'referral',
    utmCampaign: 'pesquisa-educacao',
    notes: 'Projeto acadêmico. Timeline longa, orçamento médio. Pode gerar publicações e reconhecimento. Avaliar.',
  },

  // 🎪 CURIOSO EXPLORADOR - Festival Alternativo
  {
    name: 'Larissa Costa',
    email: 'larissa.costa@festivalalternativo.com',
    phone: '(21) 81111-8888',
    company: 'Festival Alternativo de Arte e Tecnologia',
    position: 'Produtora Cultural',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação para Festival Underground',
    budget: 'R$ 40.000 - R$ 70.000',
    timeline: '3 meses',
    description: 'Oi! Vi o trabalho de vocês e fiquei MUITO curiosa! Fazemos um festival alternativo e queremos algo diferente, fora da caixa. Não temos muito orçamento, mas temos muito amor e visibilidade. Seria incrível ter algo da Azimut no nosso festival!',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work/festivais',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'festival-alternativo',
    notes: 'Lead curioso, entusiasmado, mas orçamento baixo. Pode ser interessante para portfólio e visibilidade. Linguagem informal.',
  },

  // 🏛️ CENTRO CULTURAL - Interessado em Programação
  {
    name: 'Gabriel Souza',
    email: 'gabriel.souza@centrocultural.gov.br',
    phone: '(11) 80000-9999',
    company: 'Centro Cultural Municipal',
    position: 'Diretor de Programação Cultural',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa de Exposições Imersivas - 2026',
    budget: 'R$ 300.000 - R$ 500.000',
    timeline: '12 meses',
    description: 'Estamos planejando um programa anual de exposições imersivas. Queremos 4 exposições ao longo de 2026, cada uma com tema diferente. Precisamos de um parceiro que entenda tanto a parte técnica quanto a artística. Vocês fazem curadoria também?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'programa-exposicoes',
    notes: 'Call realizada. Cliente muito interessado. Programa anual = múltiplos projetos. Potencial de longo prazo. Anick + você devem participar da próxima reunião.',
    lastContactAt: new Date('2025-12-29T11:00:00Z'),
  },

  // 🎯 ALTO DESEMPENHO - Marca Premium
  {
    name: 'Mariana Lima',
    email: 'mariana.lima@marcapremium.com',
    phone: '(21) 79999-0000',
    company: 'Marca Premium Internacional',
    position: 'Diretora Global de Experiências',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Pop-up Global - 5 Cidades',
    budget: 'R$ 2.000.000 - R$ 3.500.000',
    timeline: '18 meses',
    description: 'Estamos lançando uma experiência global em 5 cidades (São Paulo, Rio, Nova York, Londres, Tóquio). Precisamos de um parceiro que possa escalar e manter qualidade em todos os locais. Vocês têm experiência internacional?',
    status: 'PROPOSAL_SENT',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'marca-premium-global',
    notes: 'Proposta enviada em 28/12. Projeto MEGA. Escopo internacional. Precisamos definir estratégia de execução. Reunião com board: 15/01.',
    lastContactAt: new Date('2025-12-28T16:30:00Z'),
  },

  // 📢 AGÊNCIAS DE PUBLICIDADE - Simulando diferentes comportamentos de navegação

  // 🎯 AGÊNCIA GRANDE - Busca parceiro para campanha
  {
    name: 'Felipe Torres',
    email: 'felipe.torres@agenciapublicidade.com.br',
    phone: '(11) 78888-1111',
    company: 'Agência Publicidade & Criação',
    position: 'Diretor de Criação',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Campanha de Lançamento - Experiência Imersiva',
    budget: 'R$ 250.000 - R$ 400.000',
    timeline: '5 meses',
    description: 'Temos um cliente grande que quer lançar produto com experiência imersiva em shopping. Precisamos de um parceiro técnico que entenda tanto a parte criativa quanto a execução. Vi o portfólio de vocês e gostei muito. Podemos conversar?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'agencia-parceiro',
    notes: 'Navegação: /work (3x), /studio, /solutions. Tempo: 12min. Visitou projetos de marcas. Agência estabelecida, cliente grande.',
  },

  // 🔍 AGÊNCIA MÉDIA - Explorando opções
  {
    name: 'Renata Alves',
    email: 'renata.alves@midiaecriacao.com',
    phone: '(21) 77777-2222',
    company: 'Mídia & Criação Agência',
    position: 'Coordenadora de Projetos Especiais',
    leadType: 'CONTACT_FORM',
    projectType: 'Ativação de Marca - Evento',
    budget: 'R$ 80.000 - R$ 150.000',
    timeline: '3 meses',
    description: 'Estamos desenvolvendo uma ativação para nosso cliente e precisamos de algo diferente. Vi alguns trabalhos de vocês e fiquei curiosa sobre o processo. Como funciona? Quanto tempo leva? Vocês fazem desde o conceito até a execução?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'ativacao-marca',
    notes: 'Navegação: /solutions (2x), /work, /studio, /academy. Tempo: 18min. Muito exploratória, lendo descrições. Parece estar pesquisando fornecedores.',
  },

  // 💡 AGÊNCIA INOVADORA - Quer aprender e aplicar
  {
    name: 'Thiago Santos',
    email: 'thiago.santos@agenciafuturo.com.br',
    phone: '(11) 76666-3333',
    company: 'Agência Futuro - Inovação Digital',
    position: 'Head de Inovação',
    leadType: 'CONTACT_FORM',
    projectType: 'Workshop + Projeto Piloto',
    budget: 'R$ 120.000 - R$ 200.000',
    timeline: '6 meses',
    description: 'Somos uma agência focada em inovação. Queremos aprender sobre VR/AR/XR para oferecer aos nossos clientes. Seria possível fazer um workshop para nossa equipe E desenvolver um projeto piloto juntos? Assim aprendemos e já entregamos algo para um cliente.',
    status: 'CONTACTED',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/academy',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'workshop-projeto',
    notes: 'Navegação: /academy (múltiplas vezes), /solutions, /work. Tempo: 22min. Interesse em aprender + aplicar. Call agendada para 05/01.',
    lastContactAt: new Date('2025-12-30T14:00:00Z'),
  },

  // 🚀 AGÊNCIA STARTUP - Orçamento apertado, muita vontade
  {
    name: 'Amanda Costa',
    email: 'amanda.costa@startupagencia.com',
    phone: '(21) 75555-4444',
    company: 'Startup Agência - Nova Geração',
    position: 'Sócia-Fundadora',
    leadType: 'CONTACT_FORM',
    projectType: 'Case para Portfólio - Pro Bono ou Custo',
    budget: 'R$ 30.000 - R$ 60.000',
    timeline: '4 meses',
    description: 'Somos uma agência nova e queremos fazer algo incrível para nosso portfólio. Não temos muito orçamento, mas temos um cliente interessante e muita vontade. Seria possível fazer algo com custo reduzido? Ou até pro bono se for um case interessante?',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'startup-agencia',
    notes: 'Navegação: /work (5x), /studio. Tempo: 8min. Orçamento baixo, mas pode ser interessante para portfólio ou case de estudo.',
  },

  // 🎨 AGÊNCIA CRIATIVA - Busca parceiro técnico
  {
    name: 'Bruno Oliveira',
    email: 'bruno.oliveira@criativagencia.com.br',
    phone: '(11) 74444-5555',
    company: 'Criativa Agência',
    position: 'Diretor Executivo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria Estratégica - Múltiplos Projetos',
    budget: 'R$ 500.000 - R$ 800.000',
    timeline: '12 meses',
    description: 'Temos vários clientes que pedem experiências imersivas, mas não temos expertise técnica. Queremos estabelecer uma parceria estratégica onde vocês executam e nós cuidamos do relacionamento e criativo. Podemos ter 3-4 projetos por ano. Interessa?',
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'referral',
    utmMedium: 'word-of-mouth',
    utmCampaign: 'parceria-estrategica',
    notes: 'Navegação: /solutions, /work, /studio (2x). Tempo: 15min. Parceria de longo prazo interessante. Proposta enviada em 27/12. Aguardando resposta.',
    lastContactAt: new Date('2025-12-27T10:30:00Z'),
  },

  // 📱 AGÊNCIA DIGITAL - Especializada em mobile, quer expandir
  {
    name: 'Juliana Martins',
    email: 'juliana.martins@digitalagencia.com',
    phone: '(21) 73333-6666',
    company: 'Digital Agência - Mobile First',
    position: 'Diretora de Novos Negócios',
    leadType: 'CONTACT_FORM',
    projectType: 'Expansão de Serviços - VR/AR',
    budget: 'R$ 150.000 - R$ 250.000',
    timeline: '6 meses',
    description: 'Somos especializados em mobile e apps, mas nossos clientes começaram a pedir experiências imersivas. Queremos expandir nosso portfólio. Vocês fazem treinamento? Ou podemos terceirizar projetos para vocês enquanto aprendemos?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/academy',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'expansao-servicos',
    notes: 'Navegação: /academy (4x), /solutions, /work. Tempo: 20min. Interesse em aprender e terceirizar. Potencial de múltiplos projetos.',
  },

  // 🏆 AGÊNCIA PREMIUM - Cliente grande, orçamento grande
  {
    name: 'Rodrigo Silva',
    email: 'rodrigo.silva@premiumagencia.com.br',
    phone: '(11) 72222-7777',
    company: 'Premium Agência - Grandes Contas',
    position: 'Diretor de Contas Estratégicas',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Campanha Nacional - Múltiplas Cidades',
    budget: 'R$ 1.500.000 - R$ 2.500.000',
    timeline: '10 meses',
    description: 'Temos um cliente Fortune 500 que quer uma campanha nacional com experiências imersivas em 8 cidades. Precisamos de um parceiro que possa escalar, manter qualidade e cumprir prazos. Vocês já fizeram algo nessa escala?',
    status: 'NEGOTIATION',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'fortune-500',
    notes: 'Navegação: /work (múltiplas vezes), /studio, /solutions. Tempo: 25min. Analisou projetos grandes. Negociando escopo e timeline. Reunião final: 10/01.',
    lastContactAt: new Date('2025-12-29T16:00:00Z'),
  },

  // 🎯 AGÊNCIA BOUTIQUE - Projeto específico, muito cuidado
  {
    name: 'Carolina Ferreira',
    email: 'carolina.ferreira@boutiqueagencia.com',
    phone: '(21) 71111-8888',
    company: 'Boutique Agência - Criação Exclusiva',
    position: 'Diretora de Criação',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação Artística - Lançamento de Produto',
    budget: 'R$ 200.000 - R$ 350.000',
    timeline: '7 meses',
    description: 'Temos um cliente de luxo que quer algo único e exclusivo. Não queremos algo genérico. Precisamos de um parceiro que entenda arte, design e tecnologia. Vi o trabalho de vocês e senti que têm essa sensibilidade. Podemos conversar sobre o conceito?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'pinterest',
    utmMedium: 'social',
    utmCampaign: 'luxo-exclusivo',
    notes: 'Navegação: /work (6x), /studio (2x). Tempo: 28min. Muito detalhista, analisou cada projeto. Cliente de luxo, precisa de cuidado especial.',
  },

  // 🔄 AGÊNCIA FULL SERVICE - Quer oferecer tudo
  {
    name: 'Marcos Rocha',
    email: 'marcos.rocha@fullserviceagencia.com.br',
    phone: '(11) 70000-9999',
    company: 'Full Service Agência - Comunicação Completa',
    position: 'Diretor de Novos Produtos',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Adição de Serviço - VR/AR como Diferencial',
    budget: 'R$ 300.000 - R$ 500.000',
    timeline: '8 meses',
    description: 'Somos uma agência full service e queremos adicionar experiências imersivas ao nosso portfólio. Precisamos de um parceiro técnico confiável. Vocês podem ser nosso fornecedor exclusivo? Quantos projetos conseguem fazer por ano?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'full-service',
    notes: 'Navegação: /solutions (3x), /work, /studio. Tempo: 16min. Busca fornecedor exclusivo. Potencial de volume. Call realizada, muito interessado.',
    lastContactAt: new Date('2025-12-30T15:00:00Z'),
  },

  // 🎬 PRODUTORA, ASSESSORIA CULTURAL, ONG, OSCIP - Diferentes perfis

  // 🎬 PRODUTORA AUDIOVISUAL - Quer expandir para imersivo
  {
    name: 'André Luiz',
    email: 'andre.luiz@produtoraaudiovisual.com.br',
    phone: '(11) 69999-1111',
    company: 'Produtora Audiovisual Independente',
    position: 'Diretor e Produtor',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Documentário Imersivo - VR',
    budget: 'R$ 180.000 - R$ 280.000',
    timeline: '8 meses',
    description: 'Somos uma produtora de documentários e queremos fazer nosso primeiro projeto em VR. Temos o conteúdo, a narrativa, mas precisamos de parceiro técnico para a parte imersiva. Vocês já trabalharam com documentários? Como funciona a produção?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'documentario-vr',
    notes: 'Navegação: /work (4x), /solutions, /studio. Tempo: 20min. Analisou projetos de museus e cultura. Produtora estabelecida, primeiro projeto imersivo.',
  },

  // 📋 ASSESSORIA CULTURAL - Prefeitura/Município
  {
    name: 'Cristina Mendes',
    email: 'cristina.mendes@assessoriacultural.gov.br',
    phone: '(21) 68888-2222',
    company: 'Assessoria de Cultura - Prefeitura Municipal',
    position: 'Assessora de Projetos Culturais',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa de Cultura Digital - Edital Público',
    budget: 'R$ 400.000 - R$ 600.000',
    timeline: '14 meses',
    description: 'Estamos lançando um edital público para programa de cultura digital. Queremos incluir experiências imersivas. Precisamos entender melhor os custos, prazos e requisitos técnicos para incluir no edital. Vocês podem nos ajudar a estruturar isso?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'edital-cultura-digital',
    notes: 'Navegação: /solutions (2x), /work, /studio. Tempo: 14min. Assessoria pública, edital em elaboração. Call realizada, muito interessada em parceria.',
    lastContactAt: new Date('2025-12-30T09:00:00Z'),
  },

  // 🌍 ONG - Projeto Social com Tecnologia
  {
    name: 'Rafaela Santos',
    email: 'rafaela.santos@ongeducacao.org.br',
    phone: '(11) 67777-3333',
    company: 'ONG Educação e Tecnologia',
    position: 'Coordenadora de Projetos',
    leadType: 'CONTACT_FORM',
    projectType: 'Projeto Social - VR para Educação em Comunidades',
    budget: 'R$ 80.000 - R$ 120.000',
    timeline: '10 meses',
    description: 'Trabalhamos com educação em comunidades carentes. Queremos usar VR para ensinar história, ciências e cultura de forma mais envolvente. Temos financiamento de fundação internacional, mas orçamento é limitado. Vocês já fizeram projetos sociais? Podem trabalhar com valores mais acessíveis?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'referral',
    utmMedium: 'word-of-mouth',
    utmCampaign: 'projeto-social',
    notes: 'Navegação: /solutions, /work, /academy. Tempo: 16min. ONG estabelecida, financiamento internacional. Projeto com impacto social. Avaliar possibilidade de desconto ou parceria.',
  },

  // 🏛️ OSCIP - Projeto Cultural com Financiamento
  {
    name: 'Daniel Costa',
    email: 'daniel.costa@oscipcultura.org.br',
    phone: '(21) 66666-4444',
    company: 'OSCIP Cultura e Inovação',
    position: 'Diretor Executivo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Centro de Memória Digital - Projeto Aprovado Lei Rouanet',
    budget: 'R$ 350.000 - R$ 500.000',
    timeline: '12 meses',
    description: 'Temos um projeto aprovado na Lei Rouanet para criar um centro de memória digital. Precisamos de parceiro técnico para desenvolver as experiências imersivas. O projeto já está captando recursos. Vocês têm experiência com projetos incentivados?',
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'lei-rouanet',
    notes: 'Navegação: /work (3x), /studio, /solutions. Tempo: 18min. OSCIP com projeto aprovado, já captando. Proposta enviada em 26/12. Aguardando aprovação do projeto.',
    lastContactAt: new Date('2025-12-26T11:00:00Z'),
  },

  // 🎭 PRODUTORA CULTURAL - Festival Independente
  {
    name: 'Vanessa Lima',
    email: 'vanessa.lima@produtoracultural.com',
    phone: '(11) 65555-5555',
    company: 'Produtora Cultural Independente',
    position: 'Produtora Executiva',
    leadType: 'CONTACT_FORM',
    projectType: 'Festival de Arte e Tecnologia - Instalações',
    budget: 'R$ 150.000 - R$ 220.000',
    timeline: '6 meses',
    description: 'Organizamos um festival anual de arte e tecnologia. Este ano queremos incluir instalações imersivas. Já temos alguns artistas confirmados, mas precisamos de suporte técnico para as instalações. Vocês trabalham com artistas? Como funciona a colaboração?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work/festivais',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'festival-arte-tech',
    notes: 'Navegação: /work/festivais (múltiplas vezes), /work, /studio. Tempo: 22min. Produtora cultural, festival estabelecido. Interesse em colaboração com artistas.',
  },

  // 🏢 ASSESSORIA CULTURAL - Empresa Privada
  {
    name: 'Luciana Almeida',
    email: 'luciana.almeida@assessoriacultural.com.br',
    phone: '(21) 64444-6666',
    company: 'Assessoria Cultural Empresarial',
    position: 'Consultora Sênior',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa de Patrocínio Cultural - Múltiplas Ações',
    budget: 'R$ 600.000 - R$ 900.000',
    timeline: '15 meses',
    description: 'Assessoramos empresas em patrocínios culturais. Temos um cliente que quer investir em cultura digital e experiências imersivas. Precisamos de um parceiro que possa desenvolver múltiplas ações ao longo do ano. Vocês têm capacidade para isso?',
    status: 'NEGOTIATION',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'patrocinio-cultural',
    notes: 'Navegação: /solutions (4x), /work, /studio. Tempo: 24min. Assessoria empresarial, cliente grande. Programa anual com múltiplas ações. Negociando escopo e valores. Reunião decisória: 12/01.',
    lastContactAt: new Date('2025-12-29T13:00:00Z'),
  },

  // 🌱 ONG AMBIENTAL - Educação Ambiental Imersiva
  {
    name: 'Pedro Henrique',
    email: 'pedro.henrique@ongambiental.org.br',
    phone: '(11) 63333-7777',
    company: 'ONG Ambiental - Preservação e Educação',
    position: 'Coordenador de Educação',
    leadType: 'CONTACT_FORM',
    projectType: 'Experiência Imersiva - Conscientização Ambiental',
    budget: 'R$ 100.000 - R$ 160.000',
    timeline: '9 meses',
    description: 'Queremos criar uma experiência imersiva para conscientizar sobre preservação ambiental. Seria para escolas e eventos. Temos financiamento de empresa parceira. Vocês já fizeram projetos de educação ambiental? Como podemos tornar isso envolvente para jovens?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'educacao-ambiental',
    notes: 'Navegação: /work (3x), /solutions, /academy. Tempo: 19min. ONG ambiental, financiamento de empresa. Projeto educativo, público jovem.',
  },

  // 🎨 OSCIP ARTE - Projeto de Inclusão
  {
    name: 'Fernanda Rocha',
    email: 'fernanda.rocha@osciparte.org.br',
    phone: '(21) 62222-8888',
    company: 'OSCIP Arte e Inclusão',
    position: 'Diretora de Projetos',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Projeto de Inclusão - Arte Acessível via VR',
    budget: 'R$ 200.000 - R$ 300.000',
    timeline: '11 meses',
    description: 'Trabalhamos com inclusão através da arte. Queremos usar VR para tornar exposições acessíveis para pessoas com mobilidade reduzida. Projeto tem financiamento público (Ministério da Cultura). Vocês têm experiência com acessibilidade em VR?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'inclusao-acessibilidade',
    notes: 'Navegação: /work (5x), /solutions, /studio. Tempo: 21min. OSCIP focada em inclusão, financiamento público. Projeto com impacto social importante. Call agendada para 08/01.',
    lastContactAt: new Date('2025-12-30T10:30:00Z'),
  },

  // 🏢 TIPOS ESPECÍFICOS DE ORGANIZAÇÕES - Baseado em estruturas reais do Brasil

  // 🎬 REALIZADORA CULTURAL SPC S.A. - Sociedade de Propósito Específico
  {
    name: 'Ricardo Mendes',
    email: 'ricardo.mendes@realizadoracultural.com.br',
    phone: '(11) 61111-9999',
    company: 'Realizadora Cultural SPC S.A.',
    position: 'Diretor Executivo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Projeto Cultural Multiplataforma - Lei Rouanet',
    budget: 'R$ 450.000 - R$ 650.000',
    timeline: '13 meses',
    description: 'Criamos uma SPC S.A. específica para um projeto cultural aprovado na Lei Rouanet. Precisamos de parceiro técnico para desenvolver as experiências imersivas. O projeto já está captando e temos prazo para execução. Vocês têm experiência com projetos incentivados?',
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'spc-cultural',
    notes: 'Navegação: /work (4x), /solutions, /studio. Tempo: 17min. SPC criada especificamente para projeto. Lei Rouanet aprovada, captando recursos. Proposta enviada em 25/12.',
    lastContactAt: new Date('2025-12-25T14:00:00Z'),
  },

  // 🔬 INSTITUTO IDG - Inovação e Desenvolvimento
  {
    name: 'Patricia Alves',
    email: 'patricia.alves@institutoidg.org.br',
    phone: '(21) 60000-0000',
    company: 'Instituto IDG - Inovação e Desenvolvimento Global',
    position: 'Diretora de Inovação',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Hub de Inovação - Laboratório de Realidades Imersivas',
    budget: 'R$ 800.000 - R$ 1.200.000',
    timeline: '16 meses',
    description: 'Somos um instituto de inovação que quer criar um laboratório de realidades imersivas. Seria um espaço para pesquisa, desenvolvimento e demonstração de tecnologias VR/AR/XR. Precisamos de parceiro que entenda tanto a parte técnica quanto a aplicação prática. Vocês fazem consultoria também?',
    status: 'NEGOTIATION',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'instituto-idg',
    notes: 'Navegação: /solutions (5x), /work, /studio, /academy. Tempo: 30min. Instituto de inovação, projeto grande. Negociando escopo e parceria estratégica. Reunião final: 14/01.',
    lastContactAt: new Date('2025-12-29T17:00:00Z'),
  },

  // 🏛️ FUNDAÇÃO CULTURAL - Projeto de Longo Prazo
  {
    name: 'Marcelo Souza',
    email: 'marcelo.souza@fundacaocultural.org.br',
    phone: '(11) 59999-1111',
    company: 'Fundação Cultural e Educacional',
    position: 'Superintendente',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa de Cultura Digital - 3 Anos',
    budget: 'R$ 1.500.000 - R$ 2.200.000',
    timeline: '36 meses',
    description: 'Temos um programa de cultura digital de longo prazo. Queremos criar múltiplas experiências imersivas ao longo de 3 anos. Precisamos de um parceiro estratégico que possa crescer conosco. Vocês têm capacidade para projetos de longo prazo?',
    status: 'CONTACTED',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'fundacao-cultural',
    notes: 'Navegação: /solutions (6x), /work, /studio. Tempo: 25min. Fundação estabelecida, programa de longo prazo. Call realizada, muito interessado. Próxima reunião: 11/01.',
    lastContactAt: new Date('2025-12-30T11:00:00Z'),
  },

  // 🎨 COLETIVO CULTURAL - Arte e Tecnologia
  {
    name: 'Larissa Costa',
    email: 'larissa.costa@coletivocultura.com',
    phone: '(21) 58888-2222',
    company: 'Coletivo Cultura e Tecnologia',
    position: 'Coordenadora',
    leadType: 'CONTACT_FORM',
    projectType: 'Instalação Coletiva - Arte Generativa',
    budget: 'R$ 90.000 - R$ 140.000',
    timeline: '5 meses',
    description: 'Somos um coletivo de artistas e desenvolvedores. Queremos criar uma instalação coletiva usando arte generativa e VR. Não temos estrutura formal, mas temos muita vontade e alguns recursos. Vocês trabalham com coletivos? Como podemos estruturar isso?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'coletivo-arte',
    notes: 'Navegação: /work (3x), /studio. Tempo: 12min. Coletivo informal, estrutura flexível. Projeto artístico, pode ser interessante para portfólio.',
  },

  // 📚 ASSOCIAÇÃO CULTURAL - Sem Fins Lucrativos
  {
    name: 'Gustavo Lima',
    email: 'gustavo.lima@associacaocultural.org.br',
    phone: '(11) 57777-3333',
    company: 'Associação Cultural Sem Fins Lucrativos',
    position: 'Presidente',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Centro de Memória Digital - Projeto Comunitário',
    budget: 'R$ 120.000 - R$ 180.000',
    timeline: '10 meses',
    description: 'Somos uma associação cultural comunitária. Queremos criar um centro de memória digital do nosso bairro usando VR. Temos apoio da prefeitura e algumas empresas locais. Vocês já fizeram projetos comunitários? Podem trabalhar com valores mais acessíveis?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'associacao-comunitaria',
    notes: 'Navegação: /work (2x), /solutions. Tempo: 10min. Associação comunitária, projeto local. Orçamento limitado, mas pode ter visibilidade.',
  },

  // 🎭 INSTITUTO CULTURAL - Foco em Pesquisa
  {
    name: 'Beatriz Rocha',
    email: 'beatriz.rocha@institutocultural.org.br',
    phone: '(21) 56666-4444',
    company: 'Instituto Cultural de Pesquisa',
    position: 'Diretora de Pesquisa',
    leadType: 'CONTACT_FORM',
    projectType: 'Pesquisa sobre Impacto de VR em Educação',
    budget: 'R$ 200.000 - R$ 300.000',
    timeline: '18 meses',
    description: 'Fazemos pesquisa sobre impacto de tecnologias imersivas em educação. Queremos desenvolver protótipos para testar com estudantes. O projeto tem financiamento de agência de fomento. Vocês podem desenvolver protótipos para pesquisa?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/academy',
    utmSource: 'academic',
    utmMedium: 'referral',
    utmCampaign: 'pesquisa-educacao',
    notes: 'Navegação: /academy (múltiplas vezes), /solutions, /work. Tempo: 23min. Instituto de pesquisa, financiamento acadêmico. Pode gerar publicações e reconhecimento.',
  },

  // 🏢 EMPRESA CULTURAL - EIRELI
  {
    name: 'Thiago Ferreira',
    email: 'thiago.ferreira@empresacultural.com.br',
    phone: '(11) 55555-5555',
    company: 'Empresa Cultural EIRELI',
    position: 'Sócio-Proprietário',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Espaço Cultural Privado - Experiências Imersivas',
    budget: 'R$ 300.000 - R$ 450.000',
    timeline: '9 meses',
    description: 'Tenho uma empresa cultural (EIRELI) e quero criar um espaço cultural privado com experiências imersivas. Seria um negócio próprio, não projeto incentivado. Vocês trabalham com empresas privadas? Como funciona o investimento?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'empresa-cultural',
    notes: 'Navegação: /solutions (3x), /work, /studio. Tempo: 15min. Empresa privada, investimento próprio. Negócio próprio, não depende de captação. Call realizada.',
    lastContactAt: new Date('2025-12-30T13:00:00Z'),
  },

  // 🌐 INSTITUTO INTERNACIONAL - Filial Brasil
  {
    name: 'Sophia Chen',
    email: 'sophia.chen@institutointernacional.org',
    phone: '(11) 54444-6666',
    company: 'Instituto Internacional de Arte e Tecnologia - Filial Brasil',
    position: 'Diretora Regional',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa Global - Hub Brasil',
    budget: 'R$ 1.200.000 - R$ 1.800.000',
    timeline: '20 meses',
    description: 'Somos uma filial brasileira de instituto internacional. Queremos criar um hub de arte e tecnologia no Brasil, conectado com nossa rede global. Precisamos de parceiro que entenda tanto o mercado local quanto tenha visão internacional. Vocês têm experiência internacional?',
    status: 'PROPOSAL_SENT',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'instituto-internacional',
    notes: 'Navegação: /work (múltiplas vezes), /studio, /solutions. Tempo: 28min. Instituto internacional, projeto grande. Proposta enviada em 24/12. Reunião com board global: 16/01.',
    lastContactAt: new Date('2025-12-24T15:00:00Z'),
  },

  // 🏆 ORGANIZAÇÕES REAIS DO MERCADO - Simulando concorrentes e parceiros conhecidos

  // 🎯 INSTITUTO REALIZANDO FUTURO - Cliente histórico (Rio Museu Olímpico)
  {
    name: 'Ana Paula Silva',
    email: 'ana.silva@realizandofuturo.org.br',
    phone: '(21) 53333-7777',
    company: 'Instituto Realizando Futuro',
    position: 'Diretora de Projetos',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Novo Projeto Cultural - Expansão do Conceito',
    budget: 'R$ 350.000 - R$ 500.000',
    timeline: '10 meses',
    description: 'Trabalhamos juntos no Rio Museu Olímpico e foi excelente! Agora temos um novo projeto cultural e queremos contar com vocês novamente. O conceito é similar, mas queremos evoluir o que fizemos. Podemos conversar?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'referral',
    utmCampaign: 'cliente-historico',
    notes: 'Cliente histórico! Trabalharam juntos no Rio Museu Olímpico. Relacionamento estabelecido. Call realizada, muito interessada em continuar parceria. Reunião agendada: 09/01.',
    lastContactAt: new Date('2025-12-30T16:00:00Z'),
  },

  // 🎨 YDREAMS GLOBAL - Concorrente/Parceiro (Brasil, listada TSX Toronto)
  {
    name: 'Carlos Eduardo',
    email: 'carlos.eduardo@ydreams.com.br',
    phone: '(11) 52222-8888',
    company: 'YDreams Global - Tecnologias Imersivas',
    position: 'Diretor de Negócios - Brasil',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Estratégica - Co-produção',
    budget: 'R$ 600.000 - R$ 900.000',
    timeline: '12 meses',
    description: 'Conhecemos o trabalho de vocês e ficamos impressionados. Estamos desenvolvendo um projeto grande e pensamos em uma co-produção. Vocês têm interesse em parcerias? Como funciona? Somos listados na TSX Ventures (Toronto) e temos mais de 900 projetos desenvolvidos.',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'parceria-coproducao',
    notes: 'Navegação: /work (6x), /studio (2x), /solutions. Tempo: 24min. YDreams Global (Brasil) - listada TSX Toronto, escritórios SP/RJ, +900 projetos. Concorrente mas também pode ser parceiro. Interesse em co-produção. Avaliar estratégia.',
  },

  // 💡 THE LED - Especialista em LED e Projeção
  {
    name: 'Roberta Martins',
    email: 'roberta.martins@theled.com.br',
    phone: '(21) 51111-9999',
    company: 'The LED - Tecnologia em Projeção',
    position: 'Gerente de Projetos Especiais',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Projeto Conjunto - LED + VR/AR',
    budget: 'R$ 400.000 - R$ 600.000',
    timeline: '8 meses',
    description: 'Somos especialistas em LED e projeção mapeada. Temos um cliente que quer combinar nossas tecnologias com VR/AR. Vocês trabalham com projeção também? Podemos fazer um projeto conjunto?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'projeto-conjunto',
    notes: 'Navegação: /solutions (3x), /work. Tempo: 14min. The LED é especialista em LED, pode ser parceiro técnico. Projeto conjunto interessante.',
  },

  // 🎬 CONSPIRAÇÃO FILMES - Produtora de Cinema
  {
    name: 'Fernando Almeida',
    email: 'fernando.almeida@conspiracaofilmes.com.br',
    phone: '(21) 50000-0000',
    company: 'Conspiração Filmes',
    position: 'Diretor de Produção',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Filme com Elementos Imersivos - VR',
    budget: 'R$ 1.000.000 - R$ 1.500.000',
    timeline: '14 meses',
    description: 'Estamos desenvolvendo um filme que queremos incluir elementos imersivos. Não é um filme 100% VR, mas queremos experiências complementares. Vocês já trabalharam com cinema? Como podemos integrar?',
    status: 'PROPOSAL_SENT',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'referral',
    utmMedium: 'word-of-mouth',
    utmCampaign: 'filme-imersivo',
    notes: 'Navegação: /work (múltiplas vezes), /studio. Tempo: 26min. Conspiração Filmes é produtora estabelecida. Projeto grande, filme com elementos imersivos. Proposta enviada em 23/12. Aguardando feedback.',
    lastContactAt: new Date('2025-12-23T14:00:00Z'),
  },

  // 📺 TV GLOBO - Departamento de Produção
  {
    name: 'Mariana Costa',
    email: 'mariana.costa@globo.com',
    phone: '(21) 49999-1111',
    company: 'TV Globo - Departamento de Produção',
    position: 'Gerente de Produção de FX',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Programa Especial - Tecnologias Imersivas',
    budget: 'R$ 800.000 - R$ 1.200.000',
    timeline: '11 meses',
    description: 'Estamos desenvolvendo um programa especial sobre tecnologias imersivas. Queremos criar experiências para o público. Vocês podem desenvolver algo que seja exibido na TV e também ter versão interativa?',
    status: 'NEGOTIATION',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'tv-globo',
    notes: 'Navegação: /work (5x), /studio, /solutions. Tempo: 20min. TV Globo, departamento de produção. Projeto grande, visibilidade nacional. Negociando escopo e formato. Reunião decisória: 13/01.',
    lastContactAt: new Date('2025-12-29T15:00:00Z'),
  },

  // 🎬 GLOBO FILMES - Departamento de Cinema
  {
    name: 'Ricardo Santos',
    email: 'ricardo.santos@globofilmes.com',
    phone: '(21) 48888-2222',
    company: 'Globo Filmes',
    position: 'Coordenador de Projetos Especiais',
    leadType: 'CONTACT_FORM',
    projectType: 'Filme com Experiência Imersiva Complementar',
    budget: 'R$ 1.200.000 - R$ 1.800.000',
    timeline: '16 meses',
    description: 'Temos um filme em desenvolvimento e queremos criar uma experiência imersiva complementar. Seria lançada junto com o filme. Vocês já fizeram algo assim? Como funciona a produção?',
    status: 'NEW',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'globofilmes',
    notes: 'Navegação: /work (7x), /studio (3x). Tempo: 32min. Globo Filmes, projeto grande. Muito interessado, analisou portfólio detalhadamente. Prioridade alta.',
  },

  // 🎵 INPUTSOM - Áudio e Tecnologia
  {
    name: 'Lucas Ferreira',
    email: 'lucas.ferreira@inputsom.com.br',
    phone: '(11) 47777-3333',
    company: 'Inputsom - Áudio e Tecnologia',
    position: 'Diretor Criativo',
    leadType: 'CONTACT_FORM',
    projectType: 'Projeto Multimídia - Áudio + Visual Imersivo',
    budget: 'R$ 250.000 - R$ 380.000',
    timeline: '7 meses',
    description: 'Somos especialistas em áudio espacial e imersivo. Temos um projeto que quer combinar nosso áudio com visual imersivo de vocês. Vocês trabalham com integração de áudio? Podemos fazer algo juntos?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'audio-visual',
    notes: 'Navegação: /solutions (2x), /work, /studio. Tempo: 16min. Inputsom é especialista em áudio, pode ser parceiro. Projeto interessante de integração.',
  },

  // 🎬 PRODUTORA PEQUENA - Independente
  {
    name: 'Gabriela Lima',
    email: 'gabriela.lima@produtoraindependente.com',
    phone: '(21) 46666-4444',
    company: 'Produtora Independente Pequena',
    position: 'Produtora Executiva',
    leadType: 'CONTACT_FORM',
    projectType: 'Documentário Curta - Primeiro Projeto Imersivo',
    budget: 'R$ 60.000 - R$ 100.000',
    timeline: '6 meses',
    description: 'Somos uma produtora pequena e independente. Queremos fazer nosso primeiro projeto imersivo. Não temos muito orçamento, mas temos muita vontade e um projeto interessante. Vocês trabalham com orçamentos menores?',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'produtora-pequena',
    notes: 'Navegação: /work (3x), /studio. Tempo: 11min. Produtora pequena, primeiro projeto imersivo. Orçamento limitado, mas pode ser interessante para portfólio.',
  },

  // 🎭 PRODUTORA MÉDIA - Estabelecida
  {
    name: 'Paulo Henrique',
    email: 'paulo.henrique@produtoramedia.com.br',
    phone: '(11) 45555-5555',
    company: 'Produtora Média Estabelecida',
    position: 'Diretor',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Série Documental - Elementos Imersivos',
    budget: 'R$ 500.000 - R$ 750.000',
    timeline: '12 meses',
    description: 'Estamos produzindo uma série documental e queremos incluir elementos imersivos em alguns episódios. Vocês já trabalharam com séries? Como funciona a produção episódica?',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'serie-documental',
    notes: 'Navegação: /work (4x), /solutions, /studio. Tempo: 19min. Produtora estabelecida, série documental. Call realizada, muito interessado. Próxima reunião: 07/01.',
    lastContactAt: new Date('2025-12-30T12:00:00Z'),
  },

  // 🎬 PRODUTORA GRANDE - Estúdio
  {
    name: 'Isabela Rocha',
    email: 'isabela.rocha@estudioproducoes.com.br',
    phone: '(21) 44444-6666',
    company: 'Estúdio de Produções - Grande Porte',
    position: 'Diretora de Novos Formatos',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Divisão de Conteúdo Imersivo - Múltiplos Projetos',
    budget: 'R$ 2.000.000 - R$ 3.000.000',
    timeline: '24 meses',
    description: 'Estamos criando uma divisão de conteúdo imersivo. Queremos um parceiro estratégico para desenvolver múltiplos projetos ao longo de 2 anos. Vocês têm capacidade para isso? Quantos projetos conseguem fazer simultaneamente?',
    status: 'PROPOSAL_SENT',
    priority: 'URGENT',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'divisao-imersivo',
    notes: 'Navegação: /solutions (5x), /work, /studio. Tempo: 27min. Estúdio grande, divisão nova. Parceria estratégica de longo prazo. Proposta enviada em 22/12. Reunião com diretoria: 17/01.',
    lastContactAt: new Date('2025-12-22T16:00:00Z'),
  },

  // 🇨🇦 PRODUTORAS CANADENSES - Mercado internacional (baseado em pesquisa)

  // 🎬 NATIONAL FILM BOARD CANADA (NFB) - Produtora pública
  {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@nfb.ca',
    phone: '+1 (514) 283-9000',
    company: 'National Film Board of Canada (NFB)',
    position: 'Producer - Interactive & Immersive Content',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Co-produção Internacional - Documentário Imersivo',
    budget: 'CAD 400.000 - CAD 600.000',
    timeline: '14 meses',
    description: 'We are developing an immersive documentary project and looking for international co-production partners. We know your work and would like to explore collaboration. Do you have experience with international co-productions?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'nfb-coproducao',
    notes: 'Navegação: /work (múltiplas vezes), /studio, /solutions. Tempo: 22min. NFB Canada - produtora pública canadense, referência mundial em documentários. Co-produção internacional interessante. Projeto grande.',
  },

  // 🎨 FELIX & PAUL STUDIOS - Especialista em VR Cinema
  {
    name: 'Michael Felix',
    email: 'michael.felix@felixandpaul.com',
    phone: '+1 (514) 844-2020',
    company: 'Felix & Paul Studios - VR Cinema',
    position: 'Co-Founder & Creative Director',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Técnica - Projeto VR Cinema',
    budget: 'CAD 500.000 - CAD 800.000',
    timeline: '16 meses',
    description: 'We are world leaders in VR cinema and immersive storytelling. We are exploring partnerships with studios in Latin America. Your work caught our attention. Would you be interested in a technical partnership?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'felix-paul-partnership',
    notes: 'Navegação: /work (8x), /studio (3x). Tempo: 28min. Felix & Paul Studios - referência mundial em VR cinema (Montreal). Parceria técnica interessante. Projeto grande, visibilidade internacional.',
  },

  // 🏛️ ONF CANADA - Office National du Film
  {
    name: 'Jean-Pierre Dubois',
    email: 'jean.dubois@onf.ca',
    phone: '+1 (514) 283-9000',
    company: 'Office National du Film du Canada (ONF)',
    position: 'Producteur - Contenu Immersif',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Co-production Internationale - Projet Immersif',
    budget: 'CAD 350.000 - CAD 550.000',
    timeline: '13 meses',
    description: 'Nous développons un projet immersif et cherchons des partenaires de co-production internationaux. Votre travail nous intéresse. Avez-vous de l\'expérience avec les co-productions internationales?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'direct',
    utmMedium: 'email',
    utmCampaign: 'onf-coproduction',
    notes: 'Navegação: /work (4x), /studio, /solutions. Tempo: 18min. ONF Canada - produtora pública francófona (Montreal). Co-produção internacional. Projeto interessante.',
  },

  // 🎬 METAVRSE - Toronto, Canadá
  {
    name: 'David Smith',
    email: 'david.smith@metavrse.com',
    phone: '+1 (416) 555-0100',
    company: 'MetaVRse - Toronto',
    position: 'Business Development Director',
    leadType: 'CONTACT_FORM',
    projectType: 'Strategic Partnership - AR/VR Solutions',
    budget: 'CAD 300.000 - CAD 500.000',
    timeline: '11 meses',
    description: 'We are a Toronto-based AR/VR solutions company. We are expanding to Latin America and looking for strategic partners. Your portfolio impressed us. Would you be interested in discussing a partnership?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'metavrse-partnership',
    notes: 'Navegação: /solutions (3x), /work, /studio. Tempo: 16min. MetaVRse Toronto - soluções AR/VR para varejo, saúde, educação. Expansão para América Latina. Parceria estratégica interessante.',
  },

  // 🎯 NEX TECH AR - Vancouver, Canadá
  {
    name: 'Jennifer Lee',
    email: 'jennifer.lee@nextechar.com',
    phone: '+1 (604) 555-0200',
    company: 'NexTech AR Solutions - Vancouver',
    position: 'VP of Partnerships',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Partnership - AR Platform Expansion',
    budget: 'CAD 400.000 - CAD 600.000',
    timeline: '12 meses',
    description: 'We provide AR platforms for e-commerce, education and virtual events. We are looking for partners in Brazil to expand our platform. Your expertise in immersive experiences would be valuable. Interested?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'linkedin',
    utmMedium: 'social',
    utmCampaign: 'nextech-partnership',
    notes: 'Navegação: /solutions (4x), /work. Tempo: 14min. NexTech AR Vancouver - plataformas AR para e-commerce, educação, eventos. Expansão para Brasil. Parceria de distribuição interessante.',
  },

  // 🎨 IMAGINEAR - Vancouver, Canadá
  {
    name: 'Robert Chen',
    email: 'robert.chen@imaginear.com',
    phone: '+1 (604) 555-0300',
    company: 'ImagineAR - Vancouver',
    position: 'Director of Business Development',
    leadType: 'CONTACT_FORM',
    projectType: 'Partnership - AR Platform for Events',
    budget: 'CAD 250.000 - CAD 400.000',
    timeline: '10 meses',
    description: 'We offer AR platform for creating interactive experiences. We are expanding globally and Brazil is a key market. Would you be interested in becoming a partner/reseller?',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'imaginear-partnership',
    notes: 'Navegação: /solutions (2x), /work. Tempo: 12min. ImagineAR Vancouver - plataforma AR para experiências interativas. Busca parceiros/resellers no Brasil. Avaliar oportunidade.',
  },

  // 🔬 DEVOLAB - Laboratório de Desenvolvimento (simulação)
  {
    name: 'Alexandre Costa',
    email: 'alexandre.costa@devolab.com.br',
    phone: '(11) 43333-7777',
    company: 'Devolab - Laboratório de Desenvolvimento Imersivo',
    position: 'Diretor de Inovação',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Técnica - Desenvolvimento de Tecnologias',
    budget: 'R$ 300.000 - R$ 450.000',
    timeline: '10 meses',
    description: 'Somos um laboratório de desenvolvimento focado em tecnologias imersivas. Estamos desenvolvendo novas soluções e buscamos parceiros técnicos. Vocês têm interesse em colaboração em R&D?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'google',
    utmMedium: 'organic',
    utmCampaign: 'devolab-partnership',
    notes: 'Navegação: /solutions (3x), /work, /studio. Tempo: 17min. Devolab - laboratório de desenvolvimento. Parceria em R&D interessante. Pode gerar inovações.',
  },

  // 🏛️ MEMBROS XRBR - Associação Brasileira de Realidade Estendida

  // 🎮 ARVORE - Estúdio de Entretenimento Imersivo (membro XRBR)
  {
    name: 'Rodrigo Terra',
    email: 'rodrigo.terra@arvore.com.br',
    phone: '(11) 55555-1111',
    company: 'ARVORE - Estúdio de Entretenimento Imersivo',
    position: 'Co-Founder & CEO',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Estratégica - Co-produção de Jogos VR',
    budget: 'R$ 800.000 - R$ 1.200.000',
    timeline: '18 meses',
    description: 'Somos membros da XRBR junto com vocês. Estamos desenvolvendo um projeto grande de jogo VR e pensamos em uma co-produção. Vocês têm experiência com jogos imersivos? Podemos aliar nossa expertise técnica com a direção de arte de vocês.',
    status: 'CONTACTED',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'arvore-coproducao',
    notes: 'Navegação: /work (7x), /studio (3x), /solutions. Tempo: 31min. ARVORE - membro XRBR, referência em jogos VR. Co-produção estratégica interessante. Primeiro contato realizado em 28/12. Reunião agendada: 10/01.',
    lastContactAt: new Date('2025-12-28T14:30:00Z'),
  },

  // 🎨 VOCS / MoreThanReal - Tecnologias AR/VR (membro XRBR)
  {
    name: 'Leo Ferro',
    email: 'leo.ferro@morethanreal.com.br',
    phone: '(11) 66666-2222',
    company: 'VOCS / MoreThanReal - Tecnologias Imersivas',
    position: 'Diretor de Inovação',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria Técnica - Desenvolvimento de Plataforma',
    budget: 'R$ 500.000 - R$ 750.000',
    timeline: '14 meses',
    description: 'Conhecemos vocês através da XRBR. Estamos desenvolvendo uma nova plataforma de AR e precisamos de parceiros técnicos. Vocês têm interesse em colaborar? Podemos dividir custos e compartilhar tecnologia.',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'vocs-partnership',
    notes: 'Navegação: /solutions (4x), /work, /studio. Tempo: 19min. VOCS/MoreThanReal - membro XRBR, tecnologias AR/VR. Parceria técnica interessante. Contato via associação.',
  },

  // 🎬 STUDIO KWO - Produção VR (membro XRBR)
  {
    name: 'Francisco Almendra',
    email: 'francisco.almendra@studiokwo.com.br',
    phone: '(21) 77777-3333',
    company: 'Studio Kwo - Produção de Realidade Virtual',
    position: 'Diretor Criativo',
    leadType: 'CONTACT_FORM',
    projectType: 'Co-produção - Documentário VR',
    budget: 'R$ 400.000 - R$ 600.000',
    timeline: '12 meses',
    description: 'Somos membros da XRBR. Estamos produzindo um documentário VR e buscamos parceiros para co-produção. Vocês têm experiência com documentários imersivos? Podemos trabalhar juntos?',
    status: 'PROPOSAL_SENT',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'studiokwo-coproducao',
    notes: 'Navegação: /work (5x), /studio, /solutions. Tempo: 22min. Studio Kwo - membro XRBR, produção VR. Co-produção documentário. Proposta enviada em 29/12. Aguardando resposta.',
    lastContactAt: new Date('2025-12-29T11:00:00Z'),
  },

  // 🎯 BEENOCULUS - Soluções VR (membro XRBR)
  {
    name: 'Rawlinson Terrabuio',
    email: 'rawlinson@beenoculus.com.br',
    phone: '(11) 88888-4444',
    company: 'Beenoculus - Soluções em Realidade Virtual',
    position: 'CEO & Founder',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria Comercial - Distribuição de Soluções',
    budget: 'R$ 300.000 - R$ 500.000',
    timeline: '10 meses',
    description: 'Conhecemos vocês na XRBR. Temos soluções VR para diferentes setores e estamos buscando parceiros para distribuição. Vocês têm interesse em representar nossos produtos? Podemos criar uma parceria win-win.',
    status: 'NEGOTIATION',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'beenoculus-distribuicao',
    notes: 'Navegação: /solutions (3x), /work. Tempo: 16min. Beenoculus - membro XRBR, soluções VR. Parceria comercial/distribuição. Em negociação desde 26/12. Reunião: 08/01.',
    lastContactAt: new Date('2025-12-30T15:00:00Z'),
  },

  // 🎥 22PRO - Produtora XR (membro XRBR)
  {
    name: 'Fernanda Martins',
    email: 'fernanda.martins@22pro.com.br',
    phone: '(11) 99999-5555',
    company: '22PRO - Produtora de Realidade Estendida',
    position: 'Diretora de Produção',
    leadType: 'CONTACT_FORM',
    projectType: 'Subcontratação - Projeto Corporativo VR',
    budget: 'R$ 250.000 - R$ 400.000',
    timeline: '8 meses',
    description: 'Somos membros da XRBR. Temos um projeto corporativo grande e precisamos de apoio técnico. Vocês podem fazer parte da produção? Podemos dividir o projeto.',
    status: 'CONTACTED',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: '22pro-subcontratacao',
    notes: 'Navegação: /work (4x), /solutions, /studio. Tempo: 18min. 22PRO - membro XRBR, produtora XR. Subcontratação projeto corporativo. Contato realizado em 27/12. Proposta em elaboração.',
    lastContactAt: new Date('2025-12-27T10:00:00Z'),
  },

  // 🎨 VRXP - Experiências VR (membro XRBR)
  {
    name: 'Alexandre Calil',
    email: 'alexandre.calil@vrxp.com.br',
    phone: '(21) 11111-6666',
    company: 'VRXP - Experiências de Realidade Virtual',
    position: 'Diretor Executivo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria - Evento XRBR Summit',
    budget: 'R$ 150.000 - R$ 250.000',
    timeline: '6 meses',
    description: 'Conhecemos vocês na XRBR. Estamos organizando uma experiência imersiva para o próximo XRBR Summit e queremos trabalhar com vocês. Vocês têm interesse? Seria uma ótima visibilidade para ambos.',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'vrxp-summit',
    notes: 'Navegação: /work (2x), /studio. Tempo: 12min. VRXP - membro XRBR, experiências VR. Parceria para evento XRBR Summit. Visibilidade interessante.',
  },

  // 🎬 SÉTIMA CINEMA - Produções Culturais (membro XRBR)
  {
    name: 'Ana Arruda',
    email: 'ana.arruda@setimacinema.com.br',
    phone: '(11) 22222-7777',
    company: 'Sétima Cinema & Cultural Produções',
    position: 'Diretora de Projetos Culturais',
    leadType: 'CONTACT_FORM',
    projectType: 'Co-produção - Projeto Cultural Imersivo',
    budget: 'R$ 600.000 - R$ 900.000',
    timeline: '16 meses',
    description: 'Somos membros da XRBR. Estamos desenvolvendo um projeto cultural grande com Lei Rouanet aprovada. Buscamos parceiros para co-produção. Vocês têm experiência com projetos culturais imersivos?',
    status: 'PROPOSAL_SENT',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'setimacinema-coproducao',
    notes: 'Navegação: /work (6x), /studio (2x), /solutions. Tempo: 25min. Sétima Cinema - membro XRBR, produções culturais. Lei Rouanet aprovada. Co-produção interessante. Proposta enviada em 30/12.',
    lastContactAt: new Date('2025-12-30T09:00:00Z'),
  },

  // 🎯 UMATECH - Tecnologias Imersivas (suplente XRBR)
  {
    name: 'Eliza Flores',
    email: 'eliza.flores@umatech.com.br',
    phone: '(11) 33333-8888',
    company: 'UmaTech - Tecnologias Imersivas',
    position: 'Diretora de Negócios',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria Estratégica - Múltiplos Projetos',
    budget: 'R$ 700.000 - R$ 1.000.000',
    timeline: '15 meses',
    description: 'Somos suplentes no conselho da XRBR. Temos vários projetos imersivos em pipeline e buscamos parceiros estratégicos. Vocês têm interesse em uma parceria de longo prazo?',
    status: 'NEW',
    priority: 'HIGH',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'umatech-parceria',
    notes: 'Navegação: /solutions (5x), /work, /studio. Tempo: 21min. UmaTech - suplente XRBR. Parceria estratégica múltiplos projetos. Interesse alto.',
  },

  // 🎨 YDX - Inovação (suplente XRBR)
  {
    name: 'Daniel Prado',
    email: 'daniel.prado@ydx.com.br',
    phone: '(11) 44444-9999',
    company: 'YDX - Inovação em Tecnologias Imersivas',
    position: 'CEO',
    leadType: 'CONTACT_FORM',
    projectType: 'Parceria Técnica - Desenvolvimento de Produto',
    budget: 'R$ 450.000 - R$ 650.000',
    timeline: '12 meses',
    description: 'Conhecemos vocês na XRBR. Estamos desenvolvendo um novo produto imersivo e buscamos parceiros técnicos. Vocês têm interesse em colaborar? Podemos compartilhar IP e custos.',
    status: 'CONTACTED',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'ydx-parceria',
    notes: 'Navegação: /solutions (4x), /work, /studio. Tempo: 20min. YDX - suplente XRBR. Parceria técnica desenvolvimento produto. Contato realizado em 28/12.',
    lastContactAt: new Date('2025-12-28T16:00:00Z'),
  },

  // 🎵 INPUT | ARTE SONORA - Áudio Imersivo (suplente XRBR)
  {
    name: 'Mario Di Poi',
    email: 'mario.dipoi@inputsonora.com.br',
    phone: '(11) 55555-0000',
    company: 'INPUT | Arte Sonora - Áudio Imersivo',
    position: 'Diretor Criativo',
    leadType: 'BUDGET_INQUIRY',
    projectType: 'Parceria - Projeto Multimídia Imersivo',
    budget: 'R$ 350.000 - R$ 500.000',
    timeline: '10 meses',
    description: 'Somos suplentes na XRBR. Especializamos em áudio imersivo e buscamos parceiros para projetos multimídia. Vocês têm interesse em trabalhar com áudio espacial e experiências sonoras?',
    status: 'NEW',
    priority: 'MEDIUM',
    sourceUrl: 'https://azmt.com.br/solutions',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'input-parceria',
    notes: 'Navegação: /solutions (3x), /work. Tempo: 15min. INPUT - suplente XRBR, áudio imersivo. Parceria projetos multimídia. Especialização complementar interessante.',
  },

  // 🎬 BRODERS - Produções (suplente XRBR)
  {
    name: 'Bruno Pedroza',
    email: 'bruno.pedroza@broders.com.br',
    phone: '(21) 66666-1111',
    company: 'Broders - Produções Imersivas',
    position: 'Diretor de Produção',
    leadType: 'CONTACT_FORM',
    projectType: 'Co-produção - Projeto Experimental VR',
    budget: 'R$ 200.000 - R$ 350.000',
    timeline: '9 meses',
    description: 'Conhecemos vocês na XRBR. Estamos desenvolvendo um projeto experimental em VR e buscamos co-produtores. Vocês têm interesse em projetos experimentais? Podemos explorar novas narrativas juntos.',
    status: 'NEW',
    priority: 'LOW',
    sourceUrl: 'https://azmt.com.br/work',
    utmSource: 'xrbr',
    utmMedium: 'network',
    utmCampaign: 'broders-experimental',
    notes: 'Navegação: /work (3x), /studio. Tempo: 14min. Broders - suplente XRBR, produções imersivas. Projeto experimental VR. Interesse em explorar narrativas.',
  },
];

async function seedKanbanLeads() {
  console.log('🌱 Populando leads de teste para Kanban...\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  try {
    // Buscar usuários existentes para atribuir leads
    const users = await prisma.user.findMany({
      select: { id: true, email: true, name: true },
      take: 3,
    });

    if (users.length === 0) {
      console.log('⚠️  Nenhum usuário encontrado. Criando leads sem atribuição.');
    } else {
      console.log(`✅ ${users.length} usuário(s) encontrado(s) para atribuição:\n`);
      users.forEach((u, i) => {
        console.log(`   ${i + 1}. ${u.name || u.email} (${u.id.substring(0, 8)}...)`);
      });
      console.log('');
    }

    let created = 0;
    let skipped = 0;

    for (let i = 0; i < testLeads.length; i++) {
      const leadData = testLeads[i];

      // Verificar se lead já existe (por email)
      const existing = await prisma.lead.findFirst({
        where: { email: leadData.email },
      });

      if (existing) {
        console.log(`⏭️  Lead já existe: ${leadData.name} (${leadData.email})`);
        skipped++;
        continue;
      }

      // Atribuir responsável baseado no status e índice
      let assignedToId: string | null = null;
      if (users.length > 0) {
        if (leadData.status === 'NEGOTIATION' || leadData.status === 'WON') {
          // Negociação e ganhos: atribuir ao primeiro usuário (você)
          assignedToId = users[0].id;
        } else if (leadData.status === 'PROPOSAL_SENT') {
          // Propostas: atribuir ao segundo usuário (Alberto, se existir)
          assignedToId = users[1]?.id || users[0].id;
        } else if (leadData.status === 'CONTACTED' && i % 2 === 0) {
          // Alguns contatos: atribuir ao terceiro usuário (Anick, se existir)
          assignedToId = users[2]?.id || users[0].id;
        }
      }

      // Criar lead
      const lead = await prisma.lead.create({
        data: {
          ...leadData,
          assignedToId,
          assignedAt: assignedToId ? new Date() : null,
          createdAt: new Date(Date.now() - (testLeads.length - i) * 24 * 60 * 60 * 1000), // Distribuir ao longo dos dias
        },
      });

      const assignedTo = assignedToId ? users.find(u => u.id === assignedToId) : null;
      const assignedInfo = assignedTo ? ` → ${assignedTo.name || assignedTo.email}` : '';

      console.log(`✅ Criado: ${leadData.name} (${leadData.status})${assignedInfo}`);
      created++;
    }

    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`✅ ${created} lead(s) criado(s)`);
    console.log(`⏭️  ${skipped} lead(s) já existia(m)`);
    console.log('\n🎉 Seed concluído!');

    // Estatísticas
    const stats = await prisma.lead.groupBy({
      by: ['status'],
      _count: true,
    });

    console.log('\n📊 Distribuição por Status:');
    stats.forEach((stat) => {
      const emoji = {
        NEW: '🆕',
        CONTACTED: '📞',
        PROPOSAL_SENT: '💼',
        NEGOTIATION: '🤝',
        WON: '✅',
        LOST: '❌',
      }[stat.status] || '📋';
      console.log(`   ${emoji} ${stat.status}: ${stat._count}`);
    });

  } catch (error: any) {
    console.error('\n❌ Erro ao popular leads:', error.message);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedKanbanLeads();

